# Generated by Django 6.1 on 2026-09-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('icon', models.CharField(blank=True, help_text="Класс FontAwesome, например 'fa-wifi'", max_length=50)),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='ЧПУ')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена за сутки')),
                ('max_adults', models.PositiveSmallIntegerField(default=2, verbose_name='Макс. взрослых')),
                ('max_children', models.PositiveSmallIntegerField(default=1, verbose_name='Макс. детей')),
                ('square', models.PositiveSmallIntegerField(verbose_name='Площадь, м²')),
                ('bed_type', models.CharField(max_length=100, verbose_name='Тип кровати')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.ManyToManyField(blank=True, to='rooms.amenity', verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное фото')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Фото номера',
                'verbose_name_plural': 'Фото номеров',
            },
        ),
        migrations.CreateModel(
            name='SeasonalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Начало')),
                ('date_to', models.DateField(verbose_name='Конец')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за сутки')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Сезонная цена',
                'verbose_name_plural': 'Сезонные цены',
                'ordering': ['date_from'],
            },
        ),
    ]
