# Generated by Django 6.1 on 2026-09-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество номеров'),
        ),
    ]
