# Generated by Django 6.1 on 2026-09-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_note',
            field=models.CharField(blank=True, help_text='Например: «по запросу», «от 500 ₽», «бесплатно». Если заполнено — показывается вместо числа.', max_length=100, verbose_name='Текст цены (если не число)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена (₽)'),
        ),
    ]
